### ISSUE TITLE
Duplicate places integrations are being maintained

### ISSUE THREAD

**Issue by benmccann** [sveltejs/community-legacy#203]
https://svelte-community.netlify.app/code?tag=integrations and https://github.com/sveltejs/integrations both exist and have different lists. It would be nice to consolidate everything in one place

`sveltejs/integrations` is better organized. There are so many tags on this site that it's hard to read through them all. Perhaps categories and sub-categories would be a better way to go. E.g. "preprocessors" could be a sub-category of "integrations"

This repo could allow sorting by stars (https://github.com/sveltejs/community/issues/202) automatically, which would be really nice. That'd be harder to do on `sveltejs/integrations`

**Comment by swyxio** [comment]
thanks for starting this convo. my preference is to consolidate in a single place so that people can just find what they need (cc @antony in case he has a diff opinion)

for tag hierarchies, this is indeed a feature of more complex lists. i think we can manually maintain tag hierarchies inside the code and keep it to only two levels for now.

**Comment by benmccann** [comment]
It turns out there's now a third place :stuck_out_tongue_closed_eyes: See https://github.com/sveltejs/community/issues/281

**Comment by dreitzner** [comment]
closed in favor of https://sveltesociety.dev/
