### ISSUE TITLE
Changes in the who's using component don't seem to reflect on the site

### ISSUE THREAD

**Issue by DympyDev** [sveltejs/community-legacy#67]
So quite recently (about a week ago) my PR was merged adding our company's site to the who's using component.
Ever since I've been eagerly refreshing the svelte.dev site to see if our logo has been added, but to no prevail.
I've been watching the Svelte commits (as usual) and was hoping a new release would also trigger the site rebuild, but sadly it did not.

From what I could see in all the CI files and whatnot, there does not seem to be something in place that would trigger a site rebuild in case one of the extracted components gets updates.
Is this something that's being planned to be added?

**Comment by kevmodrome** [comment]
Hi! I think this is a manual step for the team to update the list. I'm not sure though. Maybe @Conduitry can shed some light on this?

**Comment by Conduitry** [comment]
Yeah someone just needs to deploy the site again, which I have just done. Making the site deployment more automatic is something we've been putting off because it would then require separate branches for new features that include documentation to be merged and for everything else - we don't want to document new features on the site until the release is cut. The easiest way to handle this for the time being is just to have the site deployments happen manually.
